name: Untether
targets:
  Untether:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [My App, Resources]
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.AppInstalleriOS.Untether
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SWIFT_OBJC_BRIDGING_HEADER: My App/TSUtil.h
