name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install xcodegen
       run: brew install xcodegen
     - name: Install ldid
       run: brew install ldid
     - name: Generate XCProject
       run: xcodegen generate
     - name: Build App
       run: |
            Scheme="Untether"
            XCProject="Untether.xcodeproj"
            xcodebuild -jobs $(sysctl -n hw.ncpu) -project "$XCProject" -scheme "$Scheme" -configuration Release -arch arm64 -sdk iphoneos -derivedDataPath "$TMPDIR/App" CODE_SIGNING_ALLOWED=NO DSTROOT=$AppTMP/install ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
            mkdir Payload
            mv "$(echo $TMPDIR/App/Build/Products/Release-iphoneos/*.app)" Payload
            base64 Resources/fileproviderctl_internal > "$(echo Payload/*.app)/fileproviderctl_internal"
            ldid -Sentitlements.plist "$(echo Payload/*.app)"
            zip -r9 "$Scheme.tipa" Payload
            rm -rf Payload && rm -rf "$TMPDIR/App"
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            for IPA in *.tipa; do
            git add "$IPA"
            done
            git commit -m "Built App"
            git push
